tunnel: YOUR_TUNNEL_ID
credentials-file: /etc/cloudflared/YOUR_TUNNEL_ID.json

# Origin certificate path - this fixes the main error
origincert: /etc/cloudflared/cert.pem

# Ingress rules for digidaws.site
ingress:
  # Main domain - redirect to www
  - hostname: digidaws.site
    service: http_status:301
    httpHost: www.digidaws.site
  
  # WWW subdomain - main application
  - hostname: www.digidaws.site
    service: http://localhost:8000
    originRequest:
      httpHostHeader: www.digidaws.site
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 100
      keepAliveTimeout: 90s
  
  # Catch-all rule (required)
  - service: http_status:404

# Tunnel options
logLevel: info
transport-protocol: quic

# Retry configuration for better reliability
retries: 3